# Generated by Django 2.0.6 on 2021-04-01 06:44

from django.db import migrations, models
import libs.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '远程登陆设备',
                'verbose_name_plural': '远程登陆设备',
                'db_table': 'remote_host',
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
    ]
