# Generated by Django 2.0.6 on 2021-05-16 08:33

from django.db import migrations, models
import libs.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseStepIno',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(default='', max_length=100, verbose_name='用例id')),
                ('case_test_steps', models.TextField(default='', verbose_name='用例步骤')),
                ('case_expected_result', models.TextField(default='', verbose_name='期望结果')),
            ],
            options={
                'verbose_name': '测试用例步骤和期望数据信息',
                'verbose_name_plural': '测试用例步骤和期望数据信息',
                'db_table': 'test_case_step_info',
            },
        ),
        migrations.CreateModel(
            name='TestLinkCaseInfo',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(default='', max_length=100, verbose_name='用例id')),
                ('name', models.CharField(default='', max_length=255, verbose_name='用例名称')),
                ('auto_id', models.CharField(default='', max_length=255, verbose_name='自动化id')),
                ('is_auto', models.BooleanField(default=False, verbose_name='是否自动化')),
                ('is_smoke', models.BooleanField(default=False, verbose_name='是否冒烟用例')),
                ('run_type', models.SmallIntegerField(choices=[(0, '手工'), (1, 'API自动化'), (2, 'UI自动化')], default=0, verbose_name='执行类型')),
                ('belong_to_module', models.CharField(default='', max_length=50, verbose_name='所属模块')),
                ('belong_to_testsuit', models.CharField(default='', max_length=50, verbose_name='所属用例集')),
            ],
            options={
                'verbose_name': '测试用例信息',
                'verbose_name_plural': '测试用例信息',
                'db_table': 'test_case_info',
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
    ]
